### PR TITLE
Simplify repository config

### PR DESCRIPTION
**Pull request by vinkla**
Since we're using GitHub we can use [the shorthand syntax](https://docs.npmjs.com/files/package.json#repository).

### CODE REVIEW

**Comment by PaulBGD** [comment]
I'm going to go ahead and say that this doesn't really matter, but thanks for the PR!

**Comment by vinkla** [comment]
It doesn't but this same pull request has been merged into every other Rollup plugin. One convention to rule them all.

**Comment by PaulBGD** [comment]
Well, I can't say no to that! Manually merged into #91.

**Comment by vinkla** [comment]
:+1:

**Pull request closed without merging**
