### PR TITLE
Build conflict

### PR DESCRIPTION
**Pull request by TrySound**
Ref #59

### CODE REVIEW

**Comment by TrySound** [comment]
@Victorystick Can you give me access in npm?

**Comment by ghost** [comment]
@TrySound Before you push this, could you solve the two remaining issues? 
https://github.com/rollup/rollup-plugin-typescript/issues/28
https://github.com/rollup/rollup-plugin-typescript/issues/43

The first bug is 7 month old now.

**Comment by TrySound** [comment]
@Kflash Nope. Yet.

**Pull request merged**
