### PR TITLE
Import separator fix in Windows

### PR DESCRIPTION
**Pull request by GiedriusGrabauskas**
Issue: https://github.com/rollup/rollup-plugin-typescript/issues/52

I try to debug at line [index.ts#L152](https://github.com/rollup/rollup-plugin-typescript/blob/master/src/index.ts#L152)

And that's happening because rollup function `resolveId` now gives `importer` param with OS path separators. 
Changed in [0.33.1](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0331) with this PR: https://github.com/rollup/rollup/pull/760

Before in Windows:

``` ts
importer = "D:/test/r/test/sample/overriding-typescript/main.ts"
```

Now in Windows:

``` ts
importer = "D:\\test\\r\\test\\sample\\overriding-typescript\\main.ts"
```

But Typescript `nodeModuleNameResolver` accept only with normal separator (`/`).

### CODE REVIEW

**Comment by GiedriusGrabauskas** [comment]
@Victorystick Your tests failed in newest `rollup` vesion.

**Comment by TrySound** [comment]
@GiedriusGrabauskas Can you write test which fails without your change?

**Comment by GiedriusGrabauskas** [comment]
Test `reports diagnostics and throws if errors occur during transpilation` failed with new rollup version.
Details: https://travis-ci.org/rollup/rollup-plugin-typescript/jobs/149183785

**Comment by TrySound** [comment]
Okay, then can you fix these tests?

**Comment by ghost** [comment]
@GiedriusGrabauskas  if you try to roll back the changes done in version   0.33.1 it will almost work. However some changes in version .  0.33.0 will make this fail to.

Rollup v.  0.32.4  is the latest working rollup version without this issues.

I reported this to @TrySound  earlier

**Comment by ghost** [comment]
@GiedriusGrabauskas You could try to do `process.platform === 'win32'` to check if it's windows, and if it is you can use a regExp - `x.replace('/\\/g', '/')` - to normalize the path. 

This is an expensive operation and will reduce perf with around 3 - 4 ms on huge files.

I guess this should have been done in the Rollup core, but I got reported back there isn't a bug there.

@TrySound This error is on Travis, and Travis isn't run in a Windows environment. So it has to be more then Windows triggering this.

**Comment by TrySound** [comment]
@GiedriusGrabauskas I added appveyor ci.

**Comment by TrySound** [comment]
@Kflash It's not rollup responsibility if typescript don't understand environment path type. And 3-4ms is very opinionated. It's not the case where we should think about performance. Moreover resolveId is cachable now.

**Comment by ghost** [comment]
@TrySound You need to update the dependencies and devDependencies in the repo to trigger the error.

**Comment by GiedriusGrabauskas** [comment]
I can't pass the tests on Windows, because `rollup-plugin-typescript` using `rollup-plugin-typescript@0.7.7` from npm, to rollup itself. But `0.7.7` has a critical error...

**Comment by TrySound** [comment]
X) That's a dilemma. Can you remove types and use buble transpiller for this? Temporary of course. In the next release we will fix that. Or not :)
https://www.npmjs.com/package/rollup-plugin-buble

**Comment by TrySound** [comment]
Thanks, guys!

**Pull request closed without merging**
