### PR TITLE
Prepare for rollup-1.0

### LINKED ISSUE #27: Angular2 app bundling: errors from tippex
Today I've manged to go though all the steps of packaging an Angular2 application with Rollup but had to resort to few hacks, one of the problems being https://github.com/Rich-Harris/tippex/issues/1. 

I'm opening the issue here as maybe we can find another solution not involving tippex (or even if it is fixed on the tippex side we still need a test case + version bump).

### LINKED ISSUE #80: `import xxx = require('xxx')` seems to be silently removed
### Versions
* rollup@0.39.2
* rollup-plugin-commonjs@7.0.0
* rollup-plugin-node-resolve@2.0.0
* rollup-plugin-typescript@0.8.1
* typescript@2.1.4

### `rollup.config.js`
```js
const commonjs          = require('rollup-plugin-commonjs')
const nodeRes           = require('rollup-plugin-node-resolve')
const typescript        = require('rollup-plugin-typescript')

module.exports = {
  entry    : './src/api/test.ts',
  format   : 'cjs',
  dest     : './.building/api/test.js',
  treeshake: false,
  plugins  : [
    typescript({
      typescript: require('typescript'),
    }),
    commonjs(),
    nodeRes({
      extensions: ['.ts', '.js', '.json'],
    }),
  ],
}
```

### `test.ts` (input)
```ts
// Start

import lodash = require('lodash')
console.log(lodash)

// End
```

### `test.js` (output)
```js
// Above are typescript helpers, like `__assign`, `__awaiter`, etc....

// Start
console.log(lodash);
// End
```

### LINKED ISSUE #94: Overwrites .bin/tsc.cmd
After installing it overwrites node_modules/.bin/tsc.cmd meaning that any script in package.json that just do a tsc, like tests, now picks an old 1.8 version.

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\rollup-plugin-typescript\node_modules\typescript\bin\tsc" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\rollup-plugin-typescript\node_modules\typescript\bin\tsc" %*
)
```

It should leave the original.

### LINKED ISSUE #96: Zero-byte in output
Hello, I'm experimenting with this plugin, and trying to achieve smooth experience both for frontend and backend builds.

For now I got pretty simple setup for «backend»:
```js
return rollup(
{
	entry: entry, // '.ts' file
	external: id => id !== entry, // mark everything as external
	plugins: ts(
	{
		typescript: require('typescript')
	}),
})
.then(bundle =>
{
	return bundle.generate(
	{
		format:  'cjs',
		exports: 'auto',
	})
})
```
Somehow NUL-byte is inserted inside `require('typescript-helpers');`.
I see `'\'use strict\';\n\nrequire(\'\u0000typescript-helpers\');\n…` when I debug output.
What on earth could cause this weird insertion to happen?

* `rollup@0.49.2`
* `rollup-plugin-typescript@0.8.1`
* `typescript@2.5.2`
* node `v7.5.0`

### LINKED ISSUE #110: Support tsconfig as file path
I'm working on a project that has Typescript code for browser and Node environments. Each have seperate tsconfig files. 

The current logic looks like it searches for a `tsconfig.json` file in the current working directory, meaning I can't use a different config file in a subdirectory.

Would you be open to using `tsconfig` option as a boolean or string path?

```javascript
plugins: [
      typescriptPlugin({
        tsconfig: path.join(__dirname, 'src', 'client', 'tsconfig.json'),
        typescript: require('typescript'),
      }),
    ],
```

### LINKED ISSUE #111: Add examples of different kinds of expected input
Looking at your readme I'm struggling to tell what is expected for input.

Currently trying to add tsconfig options to the plugin directly (not use tsconfig.json) and nothing it working and I'm getting `rollup-plugin-typescript: Unknown compiler option 'compilerOptions'` ad I'm not sure why this is thrown or what is expected.

### LINKED ISSUE #112: Support "ES2015" and "es2015"
Typescript is fine with upper or lowser case for "es2015" would be a plug for this module to do the same.

### LINKED ISSUE #113: Support newer typescript
I wanted to package rollup-plugin-typescript in Debian, but the testsuite doesn't work. It might be due to the fact that we have typescript 2.7.2 (the latest) and this plugin knows about 1.8.9...

Could you support newer typescript?

Thanks

Snark on #debian-js

### LINKED ISSUE #114: Lib option results in an error
I have following `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "preserveConstEnums": true,
    "outDir": "lib",
    "sourceMap": true,
    "lib": [
      "dom",
      "es2015"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```
rollup-plugin-typescript: Unknown compiler option 'lib'.
[!] Error: rollup-plugin-typescript: Couldn't process compiler options
Error: rollup-plugin-typescript: Couldn't process compiler options
```

### LINKED ISSUE #122: broken Node.js 6 tests
`async / await` can not be used in Node.js 6.

https://ci.appveyor.com/project/TrySound/rollup-plugin-typescript/build/79

### LINKED ISSUE #123: Breaks on valid JSX code
TL&DR: Please update the `tippex` dependency.

Release 0.8.1 of `rollup-plugin-typescript` breaks on this JSX code:
```
import * as React from 'react';
const S = () => <span><img src="s" /></span>;
const C = () => {return <div />; };
```

The error message is: 
```
[!] (Plugin at pos 6 plugin) Error: rollup-plugin-typescript: Unexpected character (3:34). If this is valid JavaScript, it's probably a bug in tippex. Please raise an issue at https://github.com/Rich-Harris/tippex/issues – thanks!


const C = () => {return <div />; };

                                   ^; when processing: '…
```

As noted, this is a problem with `tippex`, but only with the outdated version 2. When using the same code in the test suite of `tippex` 3, the error did not occur anymore. 

So, please upgrade the `tippex` depedency to version 3.

### PR DESCRIPTION
**Pull request by lukastaegert**
Besides updating all dependenices, this introduces some fundamental changes, many of which are inspired by other PRs:
* Minimum TypeScript version is 2.1; version 3 is supported as well
* Instead of custom helpers, use tslib for TypeScript helpers
* Both `TypeScript` and `tslib` become peer dependencies
* Injecting a custom `tslib` is possible as well
* If the `tsconfig` option is a path, this path will be used to find a `tsconfig` file
* Support for dynamic imports
* Support for CommonJS imports if configured correctly, cf. README
* Fix an issue when no `tsconfig.json` file is present.
* Tests will work with Rollup@1.0
* Tests will run on node 7 again
* Updated readme

closes #117 
closes #104 (I believe the use of tslib makes this unnecessary)
closes #93 
resolves #123 
resolves #122 
resolves #114 
resolves #113 
resolves #112 
resolves #111 
resolves #110 
resolves #96 
resolves #94 
resolves #80 
resolves #27

### CODE REVIEW

**Comment by lukastaegert** [comment]
Feedback is of course welcome.
@Rich-Harris @TrySound @Victorystick @PaulBGD if one of you would grant me publishing rights to `rollup-plugin-typescript`, I can take care of releasing a new version.

**Comment by TrySound** [comment]
@lukastaegert Done

**Comment by lukastaegert** [comment]
Thanks!

**Comment by DanielRuf** [comment]
Node.js 7 and other odd releases are short instable ones and already reached their EOL. So it does not make much sense to use them. People use 6, 8 and 10 as 6 was the previous LTS branch.

**Pull request merged**
