### PR TITLE
Add __generator helper

### PR DESCRIPTION
**Pull request by guybedford**
This would allow the Rollup codebase to start using async/await syntax which would be super useful.

This is a complete duplicate of https://github.com/rollup/rollup-plugin-typescript/pull/72.

This was closed to work on a larger 2.0 rewrite which seems to be unfortunately stalled. Incremental progress should always win though.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
Same question as before: tests?

**Comment by guybedford** [comment]
Unfortunately the same answer would apply - they depend on TypeScript 2 :)

**Comment by guybedford** [comment]
Ping here - it would be really nice to get Rollup itself built using async/await and this is currently blocking that.

Let me know what I can do here, short of running a full TypeScript 2 upgrade?

**Comment by marvinhagemeister** [comment]
@guybedford I made a PR which uses the users typescript installation and the official helpers. See #117 .

**Pull request closed without merging**
