### PR TITLE
Specify tsconfig.json file

### PR DESCRIPTION
**Pull request by notoriousb1t**
Allows tsconfig path to be passed into the typescript options.  PR for #66 

``` javascript
{
    tsconfig: 'path/to/tsconfig.json'
}
```

### CODE REVIEW

**Comment by Narretz** [comment]
It looks like the travis build failed because of a syntax error. Maybe if you fixed it, we could get the maintainer's attention? :D

**Comment by notoriousb1t** [comment]
The travis error is because async/await is being used in one of the tests:  https://travis-ci.org/rollup/rollup-plugin-typescript/jobs/168521206

When I look at the other PRs for this, they all have the same error.  This must have been introduced either by adding a test environment to travis or by a direct commit by the maintainer.

I'm starting to get the sense that this repository has been abandoned due to the lack of activity on it.

**Comment by unional** [comment]
Does anyone want to pick this up? I also need this PR.

Ping @eventualbuddha @TrySound @maxdavidson

**Comment by unional** [comment]
@notoriousb1t can you try updating the typescript dependency to 2.1.4? That should solve the travis error.

**Comment by notoriousb1t** [comment]
I should be able to do that in a little bit

**Comment by unional** [comment]
Um... it is complaining the helper methods not generated. Likely need a config file. It should work out of the box. Need to try create a some repo to pin point it.

**Comment by unional** [comment]
By the way, for now, I'm following this: https://github.com/maxdavidson/typescript-library-boilerplate and it is working well.

**Comment by notoriousb1t** [comment]
It looks like this repo is specifying helpers directly, so this PR won't work until this one is accepted https://github.com/rollup/rollup-plugin-typescript/pull/75/files#diff-3ee1ba721a3cf917fc2cf07d504b037a and the code base is remerged

**Comment by unional** [comment]
Wow, I would expect to use `tslib`

**Comment by PaulBGD** [comment]
Hello, are you interested in rebasing this off the `progress` branch? If so I can get it merged in soon.

**Comment by notoriousb1t** [comment]
@PaulBGD, I swapped the PR over to target the progress branch.  I believe this should be good to go.

**Comment by PaulBGD** [comment]
Thanks!

**Pull request merged**
