### PR TITLE
Update typescript version, add __generator helper

### PR DESCRIPTION
**Pull request by dmitry-korolev**
Sup @Victorystick 
I know that this is almost a duplicate of previous two PRs, except this one should pass travis build.
Main thing about this PR - it doesn't break anything. It just allows to use newest TS features - async/await and generators.

See, just requiring latest typescript doesn't help - it works, and it transpiles, but __generator helper is not imported, and an error occures: `Push.ts:20 Uncaught (in promise) ReferenceError: __generator is not defined(…)`

### CODE REVIEW

**Comment by dmitry-korolev** [comment]
@eventualbuddha 
@Victorystick 
Bump (sorry for that)

**Review by eventualbuddha — APPROVED** [review]
Seems fine to me. I'll merge if there are no objections, @Victorystick.

**Comment by notoriousb1t** [comment]
@Victorystick  @eventualbuddha 

 Can this be merged?  I believe that once it is merged, it will make it possible to update to head and merge https://github.com/rollup/rollup-plugin-typescript/pull/71 as well

**Comment by dmitry-korolev** [comment]
@Victorystick 
I literally have to bump, sorry.
I would appriciate any comment from you.

**Comment by carmanchris31** [comment]
Wanted to convert my promise callback workflow to await and ran into this problem too. Are there any objections to merging?

**Comment by belohlavek** [comment]
Other PRs depend on this. Please merge.

**Comment by kazzkiq** [comment]
@eventualbuddha Its been a while since this PR, and today TypeScript released [yet another version](https://blogs.msdn.microsoft.com/typescript/2017/04/10/announcing-typescript-2-3-rc/). It would be extremely interesting to catch up with their updates as this plugin still uses an old version.

Do you guys have any news or plans to merge this PR?

**Comment by mohd-akram** [comment]
Would be great if this was merged.

**Comment by dmitry-korolev** [comment]
I suggest using an alternative package: https://github.com/alexlur/rollup-plugin-typescript
Btw, thanks @alexlur!

**Comment by PaulBGD** [comment]
For anyone following this, #91 is where it's being worked on.

**Pull request closed without merging**
