### PR TITLE
[WIP] Progress towards 2.0 support and tslib

### PR DESCRIPTION
**Pull request by PaulBGD**
Issues this PR will attempt to solve:

- #87 
- #85 
- #81 
- #67 
- #66 
- #43 

There are some other issues that I'm looking at adding with this larger PR, but for now those issues outline my goals.

### CODE REVIEW

**Comment by LukeSheard** [comment]
I've just started to use this and noticed the lack of TS2 support. What else needs doing to do this?

**Comment by PaulBGD** [comment]
@LukeSheard With this PR TS2 support is included and works. Mostly working on other issues now.

**Comment by LukeSheard** [comment]
@PaulBGD Lemme know if you want a hand. Would be happy to contribute.

**Comment by PaulBGD** [comment]
@LukeSheard Would love some more tests of the `tslib` helpers and I need to figure out a way to test that the library supports both 1.0 and 2.0.

The biggest thing I think is integrating #84, but I'm waiting on a response from @kryops on that.

**Comment by LukeSheard** [comment]
@PaulBGD I've just tried out https://github.com/ezolenko/rollup-plugin-typescript2 as well and it's pretty slick. We could probably take a lot of ideas from that.

**Comment by ezolenko** [comment]
Main difference of this plugin (after ongoing updates) and mine is error checking -- all the caching and other stuff is mainly for solving problems introduced by error checking. I'm also probably committing a few grave sins as far as using plugin API goes.

Feel free to take as much or as little as makes sense. :) Once official plugin starts supporting error checking (#43), I'll depreciate mine (unless it is faster :)).

**Comment by PaulBGD** [comment]
The only thing left before I'm ready to publish this, is that we need way more tests. All the issues I listed seem to be complete with the changes in this branch.

EDIT: also will be looking at performance, to see if there's anything we can do to improve that.

**Comment by matthew-dean** [comment]
Btw, typescript should be listed in `package.json` as a peer dependency, not a dependency IMO. That would better address issues with typescript version and remove the need to explicitly pass in TypeScript.

**Comment by PaulBGD** [comment]
@matthew-dean The issue is, we want to provide a single install way for people to get started with Rollup and TypeScript. While I agree that a lot of people that use this plugin will just install their own TypeScript version, I think including this single package will make this easier for newer users.

**Comment by goumang2010** [comment]
Is there any progress?

**Comment by PaulBGD** [comment]
@goumang2010 I'm currently trying to find the best way to support definition files, this seems to fulfill the same behavior as `tsc` but feels like a hack: https://github.com/rollup/rollup-plugin-typescript/pull/91/files#diff-1fdf421c05c1140f6d71444ea2b27638R92

**Comment by YowaiCoder** [comment]
waiting for this, I'm not considering non-official plugins or gulp-ts or whatever.

**Comment by PaulBGD** [comment]
@fightingcat Something you could help with, check if this PR just works. Ideally it should work the same or better with the current master + typescript 2.

**Comment by StreetStrider** [comment]
@PaulBGD this PR is intended to introduce `tslib`? Is it correct that `tslib` is a natural replacement for now present «synthetic» `typescript-helpers`?

**Comment by PaulBGD** [comment]
@StreetStrider Yes.

**Comment by Rich-Harris** [comment]
I've just updated this branch so that it's mergeable, but none of the tests will pass — it's giving me this error...

> Cannot find type definition file for 'react'.

...even for tests that have nothing to do with React. Any idea what's going on?

**Comment by StreetStrider** [comment]
@Rich-Harris, just checked this, I'm seeing the same thing. `@types/react` is present on my side (I believe, you have one too). That strange, because when I use this plugin it does not fail on any typecheck errors. I use `tsc` for typecheck (`--noEmit`) and Rollup + plugin for bundling/transpiling. Rollup and plugin do all the work even if any typecheck errors is present. So this error presumably have another nature.
@PaulBGD

**Comment by PaulBGD** [comment]
@Rich-Harris Yeah I updated it locally and ran into the same issue, the main thing I can figure out is that we're discovering .ts files wrong (or not letting typescript handle discovery..)

**Comment by niklashigi** [comment]
> I'm currently trying to find the best way to support definition files

@PaulBGD Any updates on this? Being able to generate `.d.ts` files for Rollup bundles would be incredibly useful.

**Comment by PaulBGD** [comment]
Sorry when I took this on I thought I had more time to work on it. I can try to spend some more time on it, but I'm definitely looking towards merging one of the better working forks back upstream.

**Comment by grahammendick** [comment]
There's a workaround for the tslib issues
1. Install tslib and rollup-plugin-node-resolve, `npm install tslib rollup-plugin-node-resolve`
2. Tell the typescript plugin to import tslib, set `importHelpers` to true.
3. Use the node resolve plugin to generate the helper code from the tslib package

```javascript
plugins: [
    rollupTypescript({
        importHelpers: true,
    }),
    nodeResolve({ jsnext: true, main: true })
]
```

**Comment by shellscape** [comment]
@PaulBGD we're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and unfortunately we don't have time as a small team to review all pending PRs before we do that. We're closing any pending feature PRs, but _**please do not delete your branch**_. We'd love for you to open a new PR for review at the new repo once that move is done. There shouldn't be too many changes, just a new file structure, so it should be relatively painless.

**Pull request closed without merging**
